# The admin password is generated by Terraform and never typed by anyone.
# No special characters: the password ends up in DATABASE_URL, where they would
# have to be URL-encoded. 32 letters and digits are strong enough.
resource "random_password" "postgres_admin" {
  length      = 32
  special     = false
  min_upper   = 1
  min_lower   = 1
  min_numeric = 1
}

# Server names are globally unique (they become part of a public DNS name),
# so a random suffix avoids collisions.
resource "random_string" "postgres_suffix" {
  length  = 6
  upper   = false
  special = false
}

resource "azurerm_postgresql_flexible_server" "main" {
  name                = "psql-${var.project_name}-${var.environment}-${random_string.postgres_suffix.result}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  version    = var.postgres_version
  sku_name   = var.postgres_sku
  storage_mb = var.postgres_storage_mb
  zone       = var.postgres_zone

  administrator_login    = var.postgres_admin_user
  administrator_password = random_password.postgres_admin.result

  # Private access: the server only gets an address in the delegated subnet
  # and has no public endpoint.
  delegated_subnet_id           = azurerm_subnet.postgres.id
  private_dns_zone_id           = azurerm_private_dns_zone.postgres.id
  public_network_access_enabled = false

  tags = local.common_tags

  # "created-on" is added after creation by the course tenant, not by us.
  lifecycle {
    ignore_changes = [tags["created-on"]]
  }

  # The DNS zone must be linked to the VNet before the server is created,
  # otherwise Azure rejects it. Nothing here references the link, so it is explicit.
  depends_on = [azurerm_private_dns_zone_virtual_network_link.postgres]
}

resource "azurerm_postgresql_flexible_server_database" "app" {
  name      = var.postgres_database_name
  server_id = azurerm_postgresql_flexible_server.main.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}
